import pypyodbc
import sys


CONNECTION_STRING = 'Driver={SQL Server Native Client 11.0};;Server=(localdb)\ProjectsV13;Database=SD2E-Protein-Design;Trusted_Connection=yes'

def dropTables():
    conn = pypyodbc.connect(CONNECTION_STRING)
    cur = conn.cursor()

    try:
        cur.execute('''
                        if object_id(N'[structural_metrics]', 'U') IS NOT NULL DROP TABLE [structural_metrics];
                        if object_id(N'[experimental_stability_scores]', 'U') IS NOT NULL DROP TABLE [experimental_stability_scores];
                        if object_id(N'[configurational_entropy]', 'U') IS NOT NULL DROP TABLE [configurational_entropy];
                        if object_id(N'[two_body_descriptors]', 'U') IS NOT NULL DROP TABLE [two_body_descriptors];
                        if object_id(N'[metadata]', 'U') IS NOT NULL DROP TABLE [metadata];
                        if object_id(N'[index_key]', 'U') IS NOT NULL DROP TABLE [index_key];''')
        cur.commit()
        print ("Dropped All Tables\n")
    except pypyodbc.ProgrammingError as e:
        print (e)

def createTables():
    conn = pypyodbc.connect(CONNECTION_STRING)
    cur = conn.cursor()

    # index table: id dataset name
    try:
        cur.execute('''
        CREATE TABLE index_key (
                        id int PRIMARY KEY IDENTITY(1,1) NOT NULL,
                        dataset NVARCHAR(255) NOT NULL,
                        timestamp DATETIME NOT NULL,
                        name NVARCHAR(255) NOT NULL);''')
        cur.commit()
        print ("index_key Table Created\n")
    except pypyodbc.ProgrammingError as e:
        print (e)

    # structural_metrics_table: id rosetta structural metrics
    try:
        cur.execute('''
        CREATE TABLE structural_metrics (
                        id int NOT NULL,
                        AlaCount int NOT NULL,
                        T1_absq int NOT NULL,
                        T1_netq int NOT NULL,
                        Tend_absq int NOT NULL,
                        Tend_netq int NOT NULL,
                        Tminus1_absq int NOT NULL,
                        Tminus1_netq int NOT NULL,
                        abego_res_profile float NOT NULL,
                        abego_res_profile_penalty float NOT NULL,
                        avg_all_frags float NOT NULL,
                        avg_best_frag float NOT NULL,
                        bb float NOT NULL,
                        buns_bb_heavy int NOT NULL,
                        buns_nonheavy int NOT NULL,
                        buns_sc_heavy int NOT NULL,
                        buried_minus_exposed float NOT NULL,
                        buried_np float NOT NULL,
                        buried_np_AFILMVWY float NOT NULL,
                        buried_np_AFILMVWY_per_res float NOT NULL,
                        buried_np_per_res float NOT NULL,
                        buried_over_exposed float NOT NULL,
                        chymo_cut_sites int NOT NULL,
                        chymo_with_LM_cut_sites float NOT NULL,
                        contact_all int NOT NULL,
                        contact_core_SASA int NOT NULL,
                        contact_core_SCN int NOT NULL,
                        contig_not_hp_avg float NOT NULL,
                        contig_not_hp_avg_norm float NOT NULL,
                        contig_not_hp_internal_max int NOT NULL,
                        contig_not_hp_max int NOT NULL,
                        degree float NOT NULL,
                        description NVARCHAR(255) NOT NULL,
                        dslf_fa13 float NOT NULL,
                        dssp NVARCHAR(255) NOT NULL,
                        entropy float NOT NULL,
                        exposed_hydrophobics float NOT NULL,
                        exposed_np_AFILMVWY float NOT NULL,
                        exposed_polars float NOT NULL,
                        exposed_total float NOT NULL,
                        fa_atr float NOT NULL,
                        fa_atr_per_res float NOT NULL,
                        fa_dun_dev float NOT NULL,
                        fa_dun_rot float NOT NULL,
                        fa_dun_semi float NOT NULL,
                        fa_elec float NOT NULL,
                        fa_intra_atr_xover4 float NOT NULL,
                        fa_intra_sol_xover4 float NOT NULL,
                        fa_intra_elec float NOT NULL,
                        fa_intra_rep_xover4 float NOT NULL,
                        fa_rep float NOT NULL,
                        fa_rep_per_res float NOT NULL,
                        fa_sol float NOT NULL,
                        frac_helix float NOT NULL,
                        frac_loop float NOT NULL,
                        frac_sheet float NOT NULL,
                        fxn_exposed_is_np float NOT NULL,
                        hbond_bb_sc float NOT NULL,
                        hbond_lr_bb float NOT NULL,
                        hbond_lr_bb_per_sheet float NOT NULL,
                        hbond_sc float NOT NULL,
                        hbond_sr_bb float NOT NULL,
                        hbond_sr_bb_per_helix float NOT NULL,
                        helix_sc float NOT NULL,
                        holes float NOT NULL,
                        hphob_sc_contacts int NOT NULL,
                        hphob_sc_degree float NOT NULL,
                        hxl_tors float NOT NULL,
                        hydrophobicity int NOT NULL,
                        largest_hphob_cluster int NOT NULL,
                        lk_ball float NOT NULL,
                        lk_ball_bridge float NOT NULL,
                        lk_ball_bridge_uncpl float NOT NULL,
                        lk_ball_iso float NOT NULL,
                        loop_sc float NOT NULL,
                        mismatch_probability float NOT NULL,
                        n_charged float NOT NULL,
                        n_hphob_clusters int NOT NULL,
                        n_hydrophobic int NOT NULL,
                        n_hydrophobic_noA int NOT NULL,
                        n_polar_core int NOT NULL,
                        n_res int NOT NULL,
                        nearest_chymo_cut_to_Cterm int NOT NULL,
                        nearest_chymo_cut_to_Nterm int NOT NULL,
                        nearest_chymo_cut_to_term int NOT NULL,
                        nearest_tryp_cut_to_Cterm int NOT NULL,
                        nearest_tryp_cut_to_Nterm int NOT NULL,
                        nearest_tryp_cut_to_term int NOT NULL,
                        net_atr_net_sol_per_res float NOT NULL,
                        net_atr_per_res float NOT NULL,
                        net_sol_per_res float NOT NULL,
                        netcharge float NOT NULL,
                        nres int NOT NULL,
                        nres_helix int NOT NULL,
                        nres_loop int NOT NULL,
                        nres_sheet int NOT NULL,
                        omega float NOT NULL,
                        one_core_each float NOT NULL,
                        p_aa_pp float NOT NULL,
                        pack float NOT NULL,
                        percent_core_SASA float NOT NULL,
                        percent_core_SCN float NOT NULL,
                        pro_close float NOT NULL,
                        rama_prepro float NOT NULL,
                        ref float NOT NULL,
                        res_count_core_SASA int NOT NULL,
                        res_count_core_SCN int NOT NULL,
                        score_per_res float NOT NULL,
                        sequence NVARCHAR(255) NOT NULL,
                        ss_contributes_core float NOT NULL,
                        ss_sc float NOT NULL,
                        sum_best_frags float NOT NULL,
                        total_score float NOT NULL,
                        tryp_cut_sites int NOT NULL,
                        two_core_each float NOT NULL,
                        worst6frags float NOT NULL,
                        worstfrag float NOT NULL,
                        timestamp DATETIME NOT NULL,
                        FOREIGN KEY ( id ) REFERENCES index_key ( id ));''')
        cur.commit()
        print ("structural_metrics Table Created\n")
    except pypyodbc.ProgrammingError as e:
        print (e)
    
    # experimental_stability_table: id experimentally determined stability measurements
    try:
        cur.execute('''
        CREATE TABLE experimental_stability_scores (
                        id int NOT NULL,
                        assay_library float NOT NULL,
                        ec50_t float NOT NULL,
                        ec50_95ci_lbound_t float NOT NULL,
                        ec50_95ci_ubound_t float NOT NULL,
                        ec50_95ci_t float NOT NULL,
                        ec50_pred_t float NOT NULL,
                        ec50_rise_t float NOT NULL,
                        stabilityscore_t float NOT NULL,
                        ec50_c float NOT NULL,
                        ec50_95ci_lbound_c float NOT NULL,
                        ec50_95ci_ubound_c float NOT NULL,
                        ec50_95ci_c float NOT NULL,
                        ec50_pred_c float NOT NULL,
                        ec50_rise_c float NOT NULL,
                        stabilityscore_c float NOT NULL,
                        stabilityscore float NOT NULL,
                        ec50_cnn_pred_t float NOT NULL,
                        ec50_cnn_pred_c float NOT NULL,
                        stabilityscore_cnn_t float NOT NULL,
                        stabilityscore_cnn_c float NOT NULL,
                        stabilityscore_cnn float NOT NULL,
                        ec50_calibrated_t float NOT NULL,
                        ec50_rise_calibrated_t float NOT NULL,
                        stabilityscore_calibrated_t float NOT NULL,
                        ec50_calibrated_c float NOT NULL,
                        ec50_rise_calibrated_c float NOT NULL,
                        stabilityscore_calibrated_c float NOT NULL,
                        stabilityscore_calibrated float NOT NULL,
                        stabilityscore_cnn_calibrated_t float NOT NULL,
                        stabilityscore_cnn_calibrated_c float NOT NULL,
                        stabilityscore_cnn_calibrated float NOT NULL,
                        timestamp DATETIME NOT NULL,
                        FOREIGN KEY ( id ) REFERENCES index_key ( id ));''')
        cur.commit()
        print ("experimental_stability Table Created\n")
    except pypyodbc.ProgrammingError as e:
        print (e)

    # configurational_entropy table: id S_PC per-residue-type Sconf
    try:
        cur.execute('''
        CREATE TABLE configurational_entropy (
                        id int NOT NULL,
                        S_PC float NOT NULL,
                        Mean_H_entropy float NOT NULL,
                        Mean_L_entropy float NOT NULL,
                        Mean_E_entropy float NOT NULL,
                        Mean_res_entropy float NOT NULL,
                        SumH_entropies float NOT NULL,
                        SumL_entropies float NOT NULL,
                        SumE_entropies float NOT NULL,
                        H_max_entropy float NOT NULL,
                        H_min_entropy float NOT NULL,
                        H_range_entropy float NOT NULL,
                        L_max_entropy float NOT NULL,
                        L_min_entropy float NOT NULL,
                        L_range_entropy float NOT NULL,
                        E_max_entropy float NOT NULL,
                        E_min_entropy float NOT NULL,
                        E_range_entropy float NOT NULL,
                        timestamp DATETIME NOT NULL,
                        FOREIGN KEY ( id ) REFERENCES index_key ( id ));''')
        cur.commit()
        print ("configurational_entropy Table Created\n")
    except pypyodbc.ProgrammingError as e:
        print (e)
    
    # two_body_descriptors table: id pairwise atom data
    try:
        cur.execute('''
        CREATE TABLE two_body_descriptors (
                        id int NOT NULL,
                        HH0 float NOT NULL,
                        HH1 float NOT NULL,
                        HH2 float NOT NULL,
                        HH3 float NOT NULL,
                        HH4 float NOT NULL,
                        HH5 float NOT NULL,
                        HH6 float NOT NULL,
                        HH7 float NOT NULL,
                        HH8 float NOT NULL,
                        HH9 float NOT NULL,
                        HH10 float NOT NULL,
                        HH11 float NOT NULL,
                        HH12 float NOT NULL,
                        HH13 float NOT NULL,
                        HH14 float NOT NULL,
                        HC0 float NOT NULL,
                        HC1 float NOT NULL,
                        HC2 float NOT NULL,
                        HC3 float NOT NULL,
                        HC4 float NOT NULL,
                        HC5 float NOT NULL,
                        HC6 float NOT NULL,
                        HC7 float NOT NULL,
                        HC8 float NOT NULL,
                        HC9 float NOT NULL,
                        HC10 float NOT NULL,
                        HC11 float NOT NULL,
                        HC12 float NOT NULL,
                        HC13 float NOT NULL,
                        HC14 float NOT NULL,
                        HN0 float NOT NULL,
                        HN1 float NOT NULL,
                        HN2 float NOT NULL,
                        HN3 float NOT NULL,
                        HN4 float NOT NULL,
                        HN5 float NOT NULL,
                        HN6 float NOT NULL,
                        HN7 float NOT NULL,
                        HN8 float NOT NULL,
                        HN9 float NOT NULL,
                        HN10 float NOT NULL,
                        HN11 float NOT NULL,
                        HN12 float NOT NULL,
                        HN13 float NOT NULL,
                        HN14 float NOT NULL,
                        HO0 float NOT NULL,
                        HO1 float NOT NULL,
                        HO2 float NOT NULL,
                        HO3 float NOT NULL,
                        HO4 float NOT NULL,
                        HO5 float NOT NULL,
                        HO6 float NOT NULL,
                        HO7 float NOT NULL,
                        HO8 float NOT NULL,
                        HO9 float NOT NULL,
                        HO10 float NOT NULL,
                        HO11 float NOT NULL,
                        HO12 float NOT NULL,
                        HO13 float NOT NULL,
                        HO14 float NOT NULL,
                        HS0 float NOT NULL,
                        HS1 float NOT NULL,
                        HS2 float NOT NULL,
                        HS3 float NOT NULL,
                        HS4 float NOT NULL,
                        HS5 float NOT NULL,
                        HS6 float NOT NULL,
                        HS7 float NOT NULL,
                        HS8 float NOT NULL,
                        HS9 float NOT NULL,
                        HS10 float NOT NULL,
                        HS11 float NOT NULL,
                        HS12 float NOT NULL,
                        HS13 float NOT NULL,
                        HS14 float NOT NULL,
                        CC0 float NOT NULL,
                        CC1 float NOT NULL,
                        CC2 float NOT NULL,
                        CC3 float NOT NULL,
                        CC4 float NOT NULL,
                        CC5 float NOT NULL,
                        CC6 float NOT NULL,
                        CC7 float NOT NULL,
                        CC8 float NOT NULL,
                        CC9 float NOT NULL,
                        CC10 float NOT NULL,
                        CC11 float NOT NULL,
                        CC12 float NOT NULL,
                        CC13 float NOT NULL,
                        CC14 float NOT NULL,
                        CN0 float NOT NULL,
                        CN1 float NOT NULL,
                        CN2 float NOT NULL,
                        CN3 float NOT NULL,
                        CN4 float NOT NULL,
                        CN5 float NOT NULL,
                        CN6 float NOT NULL,
                        CN7 float NOT NULL,
                        CN8 float NOT NULL,
                        CN9 float NOT NULL,
                        CN10 float NOT NULL,
                        CN11 float NOT NULL,
                        CN12 float NOT NULL,
                        CN13 float NOT NULL,
                        CN14 float NOT NULL,
                        CO0 float NOT NULL,
                        CO1 float NOT NULL,
                        CO2 float NOT NULL,
                        CO3 float NOT NULL,
                        CO4 float NOT NULL,
                        CO5 float NOT NULL,
                        CO6 float NOT NULL,
                        CO7 float NOT NULL,
                        CO8 float NOT NULL,
                        CO9 float NOT NULL,
                        CO10 float NOT NULL,
                        CO11 float NOT NULL,
                        CO12 float NOT NULL,
                        CO13 float NOT NULL,
                        CO14 float NOT NULL,
                        CS0 float NOT NULL,
                        CS1 float NOT NULL,
                        CS2 float NOT NULL,
                        CS3 float NOT NULL,
                        CS4 float NOT NULL,
                        CS5 float NOT NULL,
                        CS6 float NOT NULL,
                        CS7 float NOT NULL,
                        CS8 float NOT NULL,
                        CS9 float NOT NULL,
                        CS10 float NOT NULL,
                        CS11 float NOT NULL,
                        CS12 float NOT NULL,
                        CS13 float NOT NULL,
                        CS14 float NOT NULL,
                        NN0 float NOT NULL,
                        NN1 float NOT NULL,
                        NN2 float NOT NULL,
                        NN3 float NOT NULL,
                        NN4 float NOT NULL,
                        NN5 float NOT NULL,
                        NN6 float NOT NULL,
                        NN7 float NOT NULL,
                        NN8 float NOT NULL,
                        NN9 float NOT NULL,
                        NN10 float NOT NULL,
                        NN11 float NOT NULL,
                        NN12 float NOT NULL,
                        NN13 float NOT NULL,
                        NN14 float NOT NULL,
                        NO0 float NOT NULL,
                        NO1 float NOT NULL,
                        NO2 float NOT NULL,
                        NO3 float NOT NULL,
                        NO4 float NOT NULL,
                        NO5 float NOT NULL,
                        NO6 float NOT NULL,
                        NO7 float NOT NULL,
                        NO8 float NOT NULL,
                        NO9 float NOT NULL,
                        NO10 float NOT NULL,
                        NO11 float NOT NULL,
                        NO12 float NOT NULL,
                        NO13 float NOT NULL,
                        NO14 float NOT NULL,
                        NS0 float NOT NULL,
                        NS1 float NOT NULL,
                        NS2 float NOT NULL,
                        NS3 float NOT NULL,
                        NS4 float NOT NULL,
                        NS5 float NOT NULL,
                        NS6 float NOT NULL,
                        NS7 float NOT NULL,
                        NS8 float NOT NULL,
                        NS9 float NOT NULL,
                        NS10 float NOT NULL,
                        NS11 float NOT NULL,
                        NS12 float NOT NULL,
                        NS13 float NOT NULL,
                        NS14 float NOT NULL,
                        OO0 float NOT NULL,
                        OO1 float NOT NULL,
                        OO2 float NOT NULL,
                        OO3 float NOT NULL,
                        OO4 float NOT NULL,
                        OO5 float NOT NULL,
                        OO6 float NOT NULL,
                        OO7 float NOT NULL,
                        OO8 float NOT NULL,
                        OO9 float NOT NULL,
                        OO10 float NOT NULL,
                        OO11 float NOT NULL,
                        OO12 float NOT NULL,
                        OO13 float NOT NULL,
                        OO14 float NOT NULL,
                        OS0 float NOT NULL,
                        OS1 float NOT NULL,
                        OS2 float NOT NULL,
                        OS3 float NOT NULL,
                        OS4 float NOT NULL,
                        OS5 float NOT NULL,
                        OS6 float NOT NULL,
                        OS7 float NOT NULL,
                        OS8 float NOT NULL,
                        OS9 float NOT NULL,
                        OS10 float NOT NULL,
                        OS11 float NOT NULL,
                        OS12 float NOT NULL,
                        OS13 float NOT NULL,
                        OS14 float NOT NULL,
                        SS0 float NOT NULL,
                        SS1 float NOT NULL,
                        SS2 float NOT NULL,
                        SS3 float NOT NULL,
                        SS4 float NOT NULL,
                        SS5 float NOT NULL,
                        SS6 float NOT NULL,
                        SS7 float NOT NULL,
                        SS8 float NOT NULL,
                        SS9 float NOT NULL,
                        SS10 float NOT NULL,
                        SS11 float NOT NULL,
                        SS12 float NOT NULL,
                        SS13 float NOT NULL,
                        SS14 float NOT NULL,
                        timestamp DATETIME NOT NULL,
                        FOREIGN KEY ( id ) REFERENCES index_key ( id ));''')
        cur.commit()
        print ("two_body_descriptors Table Created\n")
    except pypyodbc.ProgrammingError as e:
        print (e)


    # metadata table: id sequence dssp topology description
    try:
        cur.execute('''
        CREATE TABLE metadata (
                        id int NOT NULL,
                        sequence NVARCHAR(255) NOT NULL,
                        dssp NVARCHAR(255) NOT NULL,
                        topology NVARCHAR(255) NOT NULL,
                        description NVARCHAR(255) NOT NULL,
                        timestamp DATETIME NOT NULL,
                        FOREIGN KEY ( id ) REFERENCES index_key ( id ));''')
        cur.commit()
        print ("metadata Table Created\n")
    except pypyodbc.ProgrammingError as e:
        print (e)

    


def main():
    dropTables()
    createTables()

if __name__ == '__main__':
    main()